### ISSUE TITLE
TypeError: Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by Marineeee** [JimmyLaurent/hcaptcha-solver#2]
Hello ! Since yesterday, when I try to solve a captcha, it gives me an error :
`TypeError: Cannot read property 'reduce' of undefined
    at tryToSolve (C:\Users\m\Desktop\TAFF\JS\puppeteer-recaptcha-solver-master\node_modules\hcaptcha-solver\index.js:44:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async solveCaptcha (C:\Users\m\Desktop\TAFF\JS\puppeteer-recaptcha-solver-master\node_modules\hcaptcha-solver\index.js:77:22)
    at async hcaptcha (C:\Users\m\Desktop\TAFF\JS\puppeteer-recaptcha-solver-master\ng\ngv2.js:108:26)
    at async run (C:\Users\m\Desktop\TAFF\JS\puppeteer-recaptcha-solver-master\ng\ngv2.js:142:27)`

Maybe is there a problem with https://hcaptcha.com/getcaptcha request ? Thanks if you respond!

**Comment by JimmyLaurent** [comment]
They've upgraded their system, I fixed your problem but the bypass is dead for now.

**Comment by Revadike** [comment]
> They've upgraded their system, I fixed your problem but the bypass is dead for now.

What do you mean dead? I've applied your fix and it seems working fine here. Also, could you please bump your versions (both here and cf-solver)?

**Comment by JimmyLaurent** [comment]
I'm glad to hear that, I ran tests and I had some troubles solving captchas.
I made the changes and published new versions as asked ;)

**Comment by Revadike** [comment]
> I'm glad to hear that, I ran tests and I had some troubles solving captchas.
> I made the changes and published new versions as asked ;)

I think it was a fluke (perhaps captcha wasn't prompted), because now it doesn't seem to work anymore (working forever, probably retrying to solve). I should be fine implementing a service like 2captcha for cf-scraper, right?

**Comment by JimmyLaurent** [comment]
Yeah, you have one example [here](https://github.com/JimmyLaurent/cloudflare-scraper/issues/9)
